/**
 * GET /install
 *
 * Serves the macOS install script as text/plain with no-cache headers.
 * Clients fetch it via:
 *   curl -fsSL <origin>/install | bash -s -- --install-code=<uuid>
 *
 * The script body is built by string concatenation so that bash variable
 * references ($VAR, $#, $1, etc.) are literal in the output without
 * requiring per-dollar backslash escaping inside a TS template literal.
 * Only ${origin} is substituted at request time.
 *
 * File-size exception: longer than the 300-line cap (~500 lines). This file
 * is a cohesive single-purpose artifact — the route handler and the bash
 * script it serves. Splitting them would require fs reads at runtime
 * (import.meta.url resolution differs across Next.js build targets).
 *
 * Steps implemented (install-flow plan v3, full step 5 scope):
 *   1  – shell hygiene (set -euo pipefail)
 *   2  – argparse (--install-code=<uuid> and variants)
 *   3  – sanity checks (Darwin, node, curl, osacompile, codesign, PlistBuddy, lsregister)
 *   4  – umask 077
 *   5  – POST exchange → parse JSON → validate required fields
 *   6  – mkdir ~/.rove (chmod 700)
 *   7  – write ~/.rove/env (chmod 600)
 *   8  – write ~/.rove/auth.token (chmod 600)
 *   9  – download tarballs from <origin>/install/
 *   10 – npm install into ~/.rove/lib/; verify rove.js exists
 *   11 – write LaunchAgent plist with literal absolute paths (step 4)
 *   12 – launchctl bootout → bootstrap → enable → kickstart (step 4)
 *   13 – generate AppleScript applet source (paths substituted before osacompile)
 *   14 – compile applet + patch Info.plist for rove:// URL scheme
 *   15 – write ~/.rove/url-handler.sh (chmod 700) — action dispatcher
 *   16 – ad-hoc codesign the .app
 *   17 – lsregister to register the URL scheme with LaunchServices
 */
import "server-only";
import { getDashboardOrigin } from "@/lib/dashboard-origin";

export const runtime = "nodejs";

/**
 * Returns a node one-liner (for embedding in a bash $(...) substitution) that
 * extracts `field` from the JSON string held in the bash variable $RESP_BODY.
 *
 * When allowNull=false the node process exits 1 and prints an error if the
 * field is absent or null.  When allowNull=true it prints an empty string.
 */
function nodeExtract(field: string, allowNull = false): string {
  const check = allowNull
    ? ""
    : `if(v===undefined||v===null){process.stderr.write("error: exchange response missing field: ${field}\\n");process.exit(1);}`;
  const out = allowNull
    ? `process.stdout.write(v==null?"":String(v));`
    : `process.stdout.write(String(v));`;
  // $NODE_BIN and $RESP_BODY are bash variables — they must appear literally
  // in the output, not be interpolated by TypeScript.
  return `"$NODE_BIN" -e 'const j=JSON.parse(process.argv[1]);const v=j["${field}"];${check}${out}' -- "$RESP_BODY"`;
}

/** Build the bash script with origin substituted in. */
function buildScript(origin: string): string {
  // Using string concatenation so that every $ in the bash body is literal.
  // Only the JS variables (origin, nodeExtract results) are interpolated here.
  const S = "$"; // shorthand so the code below reads naturally
  const lines: string[] = [
    `#!/usr/bin/env bash`,
    `# Rove macOS worker install script`,
    `# Fetched from: ${origin}/install`,
    `# Usage: curl -fsSL ${origin}/install | bash -s -- --install-code=<uuid>`,
    `#`,
    `# Implements install-flow plan v3, full step 5 scope (LaunchAgent + rove:// handler).`,
    `set -euo pipefail`,
    ``,
    `ORIGIN="${origin}"`,
    `echo "Rove installer — fetched from ${S}{ORIGIN}"`,
    `echo ""`,
    ``,
    `# ── step 1: argparse ─────────────────────────────────────────────────────`,
    `# Supports: --install-code=<uuid>  |  --install-code <uuid>  |  positional`,
    `INSTALL_CODE=""`,
    ``,
    `while [[ ${S}# -gt 0 ]]; do`,
    `  case "${S}1" in`,
    `    --install-code=*)`,
    `      INSTALL_CODE="${S}{1#--install-code=}"`,
    `      shift`,
    `      ;;`,
    `    --install-code)`,
    `      if [[ ${S}# -lt 2 ]]; then`,
    `        echo "error: --install-code requires a value" >&2`,
    `        exit 1`,
    `      fi`,
    `      INSTALL_CODE="${S}2"`,
    `      shift 2`,
    `      ;;`,
    `    *)`,
    `      if [[ -z "${S}INSTALL_CODE" && ${S}# -eq 1 ]]; then`,
    `        INSTALL_CODE="${S}1"`,
    `        shift`,
    `      else`,
    `        echo "error: unexpected argument: ${S}1" >&2`,
    `        echo "Usage: curl -fsSL ${S}{ORIGIN}/install | bash -s -- --install-code=<uuid>" >&2`,
    `        exit 1`,
    `      fi`,
    `      ;;`,
    `  esac`,
    `done`,
    ``,
    `if [[ -z "${S}INSTALL_CODE" ]]; then`,
    `  echo "error: --install-code is required" >&2`,
    `  echo "" >&2`,
    `  echo "Usage: curl -fsSL ${S}{ORIGIN}/install | bash -s -- --install-code=<uuid>" >&2`,
    `  echo "" >&2`,
    `  echo "Get an install code from ${S}{ORIGIN}/setup" >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `# ── step 2: sanity checks ────────────────────────────────────────────────`,
    `if [[ "${S}(uname -s)" != "Darwin" ]]; then`,
    `  echo "error: this installer is macOS-only. Linux and Windows support is planned." >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `if ! NODE_BIN="${S}(command -v node 2>/dev/null)"; then`,
    `  echo "error: node not found. Install Node.js (https://nodejs.org) and try again." >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `if ! command -v npm &>/dev/null; then`,
    `  echo "error: npm not found. It should ship with Node.js — check your installation." >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `if ! command -v curl &>/dev/null; then`,
    `  echo "error: curl not found. It ships with macOS; something is wrong with your PATH." >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `if ! command -v osacompile &>/dev/null; then`,
    `  echo "error: osacompile not found. It ships with macOS; something is wrong with your installation." >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `if ! command -v codesign &>/dev/null; then`,
    `  echo "error: codesign not found. It ships with Xcode Command Line Tools (xcode-select --install)." >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `PLISTBUDDY="/usr/libexec/PlistBuddy"`,
    `if [[ ! -x "${S}PLISTBUDDY" ]]; then`,
    `  echo "error: PlistBuddy not found at ${S}PLISTBUDDY. It ships with macOS." >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"`,
    `if [[ ! -x "${S}LSREGISTER" ]]; then`,
    `  echo "error: lsregister not found at ${S}LSREGISTER. It ships with macOS." >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `echo "Using node : ${S}NODE_BIN"`,
    `echo "Using npm  : ${S}(command -v npm)"`,
    `echo ""`,
    ``,
    `# ── step 3: umask ────────────────────────────────────────────────────────`,
    `# All files created from here on are locked down by default (no group/other).`,
    `umask 077`,
    ``,
    `# ── step 4: exchange install code for credentials ────────────────────────`,
    `echo "Exchanging install code with ${S}{ORIGIN}/api/install/exchange ..."`,
    ``,
    // Single-quoted JSON with $INSTALL_CODE spliced in via quote-breaking:
    //   '{"install_code":"'$INSTALL_CODE'"}'
    `EXCHANGE_BODY='{"install_code":"'` + S + `INSTALL_CODE'"}'`,
    `RESP_TMP="${S}(mktemp)"`,
    ``,
    `# Drop -f so we can capture the body on non-200 responses for better errors.`,
    `HTTP_CODE="${S}(`,
    `  curl -sSL \\`,
    `    --write-out '%{http_code}' \\`,
    `    --output "${S}RESP_TMP" \\`,
    `    -X POST "${S}{ORIGIN}/api/install/exchange" \\`,
    `    -H 'Content-Type: application/json' \\`,
    `    -d "${S}EXCHANGE_BODY"`,
    `)" || {`,
    `  rm -f "${S}RESP_TMP"`,
    `  echo "error: curl failed to reach ${S}{ORIGIN}/api/install/exchange" >&2`,
    `  exit 1`,
    `}`,
    ``,
    `RESP_BODY="${S}(cat "${S}RESP_TMP")"`,
    `rm -f "${S}RESP_TMP"`,
    ``,
    `if [[ "${S}HTTP_CODE" != "200" ]]; then`,
    `  echo "error: exchange endpoint returned HTTP ${S}HTTP_CODE" >&2`,
    `  echo "${S}RESP_BODY" >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `# Extract required fields from the JSON response via node one-liners.`,
    `# github_handle is nullable; all others are required.`,
    `TOKEN="${S}(${nodeExtract("token")})"`,
    `SUPABASE_URL="${S}(${nodeExtract("supabase_url")})"`,
    `SUPABASE_PUBLISHABLE_KEY="${S}(${nodeExtract("supabase_publishable_key")})"`,
    `PROJECT_ID="${S}(${nodeExtract("project_id")})"`,
    `WORKER_NAME="${S}(${nodeExtract("worker_name")})"`,
    `GITHUB_HANDLE="${S}(${nodeExtract("github_handle", true)})"`,
    ``,
    `echo "Credentials received for worker '${S}WORKER_NAME' in project '${S}PROJECT_ID'"`,
    `echo ""`,
    ``,
    `# ── step 5: mkdir ~/.rove (chmod 700) ────────────────────────────────────`,
    `mkdir -p "${S}HOME/.rove"`,
    `chmod 700 "${S}HOME/.rove"`,
    ``,
    `# ── step 6: write ~/.rove/env (chmod 600) ────────────────────────────────`,
    `# printf '%q' produces bash-safe quoting; the file is safely sourceable.`,
    `{`,
    `  printf 'ROVE_SUPABASE_URL=%q\\n'            "${S}SUPABASE_URL"`,
    `  printf 'ROVE_SUPABASE_PUBLISHABLE_KEY=%q\\n' "${S}SUPABASE_PUBLISHABLE_KEY"`,
    `  printf 'ROVE_DAEMON_GITHUB_HANDLE=%q\\n'    "${S}GITHUB_HANDLE"`,
    `  printf 'ROVE_WORKER_NAME=%q\\n'             "${S}WORKER_NAME"`,
    `  printf 'ROVE_PROJECT_ID=%q\\n'              "${S}PROJECT_ID"`,
    `} > "${S}HOME/.rove/env"`,
    `chmod 600 "${S}HOME/.rove/env"`,
    ``,
    `# ── step 7: write ~/.rove/auth.token (chmod 600) ─────────────────────────`,
    `printf '%s' "${S}TOKEN" > "${S}HOME/.rove/auth.token"`,
    `chmod 600 "${S}HOME/.rove/auth.token"`,
    ``,
    `echo "Credentials written to ~/.rove/"`,
    ``,
    `# ── step 8: download tarballs ────────────────────────────────────────────`,
    `echo "Downloading CLI tarballs from ${S}{ORIGIN}/install/ ..."`,
    ``,
    `curl -fsSL "${S}{ORIGIN}/install/agiterra-rove-core.tgz" -o "${S}HOME/.rove/core.tgz" || {`,
    `  echo "error: failed to download agiterra-rove-core.tgz from ${S}{ORIGIN}" >&2`,
    `  exit 1`,
    `}`,
    `curl -fsSL "${S}{ORIGIN}/install/agiterra-rove-cli.tgz" -o "${S}HOME/.rove/cli.tgz" || {`,
    `  echo "error: failed to download agiterra-rove-cli.tgz from ${S}{ORIGIN}" >&2`,
    `  exit 1`,
    `}`,
    ``,
    `echo "Tarballs downloaded."`,
    ``,
    `# ── step 9: npm install into ~/.rove/lib/ ────────────────────────────────`,
    `echo "Installing CLI into ~/.rove/lib/ (this may take ~30 seconds) ..."`,
    ``,
    `mkdir -p "${S}HOME/.rove/lib"`,
    ``,
    `# npm init -y is idempotent; re-running on an existing package.json is safe.`,
    `(cd "${S}HOME/.rove/lib" && npm init -y >/dev/null 2>&1)`,
    ``,
    `npm install --silent --no-save \\`,
    `  --prefix "${S}HOME/.rove/lib" \\`,
    `  "${S}HOME/.rove/core.tgz" "${S}HOME/.rove/cli.tgz"`,
    ``,
    `ROVE_JS="${S}HOME/.rove/lib/node_modules/@agiterra/rove-cli/bin/rove.js"`,
    ``,
    `if [[ ! -f "${S}ROVE_JS" ]]; then`,
    `  echo "error: npm install completed but ${S}ROVE_JS was not found." >&2`,
    `  echo "       Check that the tarballs from ${S}{ORIGIN}/install/ are valid." >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `echo "CLI installed at ${S}ROVE_JS"`,
    `echo ""`,
    ``,
    `# ── step 11: write LaunchAgent plist ─────────────────────────────────────`,
    `# Paths are resolved at install time and substituted literally into the
    # plist. launchd runs with a sparse PATH; never use env/which inside the
    # plist. ROVE_WORKER_TOKEN_FILE points at the token file — the token itself
    # never appears in the plist so launchctl print does not leak it.`,
    `PLIST_DIR="${S}HOME/Library/LaunchAgents"`,
    `PLIST_PATH="${S}PLIST_DIR/com.agiterra.rove.daemon.plist"`,
    ``,
    `mkdir -p "${S}PLIST_DIR"`,
    ``,
    `echo "Writing LaunchAgent plist to ${S}PLIST_PATH ..."`,
    ``,
    `# Write XML with all paths substituted by the shell (heredoc with
    # double-quoted opener so variables expand NOW, not inside launchd).`,
    `cat > "${S}PLIST_PATH" <<PLIST_EOF`,
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`,
    `<plist version="1.0"><dict>`,
    `  <key>Label</key>          <string>com.agiterra.rove.daemon</string>`,
    `  <key>ProgramArguments</key>`,
    `  <array>`,
    `    <string>${S}NODE_BIN</string>`,
    `    <string>${S}ROVE_JS</string>`,
    `    <string>daemon</string>`,
    `    <string>--as=${S}WORKER_NAME</string>`,
    `    <string>--project-id=${S}PROJECT_ID</string>`,
    `  </array>`,
    `  <key>EnvironmentVariables</key>`,
    `  <dict>`,
    `    <key>PATH</key>                              <string>/usr/local/bin:/usr/bin:/bin</string>`,
    `    <key>ROVE_SUPABASE_URL</key>                 <string>${S}SUPABASE_URL</string>`,
    `    <key>ROVE_SUPABASE_PUBLISHABLE_KEY</key>     <string>${S}SUPABASE_PUBLISHABLE_KEY</string>`,
    `    <key>ROVE_WORKER_TOKEN_FILE</key>            <string>${S}HOME/.rove/auth.token</string>`,
    `    <key>ROVE_DAEMON_GITHUB_HANDLE</key>         <string>${S}GITHUB_HANDLE</string>`,
    `  </dict>`,
    `  <key>RunAtLoad</key>      <true/>`,
    `  <key>KeepAlive</key>`,
    `  <dict><key>SuccessfulExit</key><false/></dict>`,
    `  <key>ThrottleInterval</key> <integer>10</integer>`,
    `  <key>StandardOutPath</key>  <string>${S}HOME/.rove/daemon.log</string>`,
    `  <key>StandardErrorPath</key> <string>${S}HOME/.rove/daemon.err</string>`,
    `</dict></plist>`,
    `PLIST_EOF`,
    ``,
    `# Verify the plist is well-formed (plutil ships with macOS).`,
    `if command -v plutil &>/dev/null; then`,
    `  plutil -lint "${S}PLIST_PATH" || {`,
    `    echo "error: plist failed plutil lint — please report this" >&2`,
    `    exit 1`,
    `  }`,
    `fi`,
    ``,
    `echo "LaunchAgent plist written."`,
    `echo ""`,
    ``,
    `# ── step 12: launchctl bootstrap + enable (one-time) + kickstart ─────────`,
    `# Modern launchctl verbs — no legacy load/unload. enable runs once at
    # install time only; rove://start deliberately omits it so a user who
    # calls launchctl disable stays disabled until they re-enable explicitly.`,
    `echo "Registering and starting the daemon via launchctl ..."`,
    ``,
    `# Idempotent: bootout any previously loaded agent before re-bootstrapping.`,
    `launchctl bootout gui/${S}UID "${S}PLIST_PATH" 2>/dev/null || true`,
    `launchctl bootstrap gui/${S}UID "${S}PLIST_PATH"`,
    `# Install-time only: mark the agent as enabled in launchd's persistent DB.`,
    `launchctl enable    gui/${S}UID/com.agiterra.rove.daemon`,
    `# Force an immediate start (bypasses RunAtLoad delay on re-install).`,
    `launchctl kickstart -k gui/${S}UID/com.agiterra.rove.daemon`,
    ``,
    `echo "Daemon installed and started."`,
    `echo ""`,
    ``,
    `# ── step 13: write ~/.rove/url-handler.sh (chmod 700) ────────────────────`,
    `# The handler reads worker_name + project_id from ~/.rove/env only.
    # URL query params are ignored — any site can craft rove://start?evil=1.
    # Action enum is closed: start | stop | restart | reveal-logs.
    # rove://start deliberately omits launchctl enable (reviewer cheatsheet #16).
    # rove://stop uses bootout only — not disable (reviewer cheatsheet #8).`,
    `URL_HANDLER="${S}HOME/.rove/url-handler.sh"`,
    ``,
    // Build the url-handler.sh content using string concatenation so that
    // bash parameter expansions like ${url#rove://} and ${action%%[?/]*}
    // are NOT interpreted by TypeScript's template literal parser.
    // S = "$" is defined at the top of buildScript().
    `cat > "${S}URL_HANDLER" <<'HANDLER_EOF'`,
    `#!/bin/bash`,
    `set -euo pipefail`,
    ``,
    `# Source trusted local config — never accept worker_name/project_id from URL.`,
    `ENV_FILE="$HOME/.rove/env"`,
    `if [[ -f "$ENV_FILE" ]]; then`,
    `  # shellcheck source=/dev/null`,
    `  source "$ENV_FILE"`,
    `fi`,
    ``,
    `# Parse only the action keyword from the URL. Strip everything from ? or / onward.`,
    `url="$1"`,
    "action=\"" + S + "{url#rove://}\"",
    "action=\"" + S + "{action%%[?/]*}\"",
    ``,
    `PLIST="$HOME/Library/LaunchAgents/com.agiterra.rove.daemon.plist"`,
    ``,
    `case "$action" in`,
    `  start)`,
    `    # Bootstrap loads the agent; kickstart forces immediate start.`,
    `    # IMPORTANT: do NOT call launchctl enable here — the URL handler must`,
    `    # not override a user's deliberate launchctl disable or admin disable.`,
    `    launchctl bootstrap gui/$UID "$PLIST" 2>/dev/null || true`,
    `    launchctl kickstart -k gui/$UID/com.agiterra.rove.daemon 2>/dev/null || true`,
    `    ;;`,
    `  stop)`,
    `    # Session-scoped pause. Next login (or re-bootstrap) restarts.`,
    `    # IMPORTANT: do NOT call launchctl disable — that's the admin path.`,
    `    launchctl bootout gui/$UID "$PLIST" 2>/dev/null || true`,
    `    ;;`,
    `  restart)`,
    `    launchctl bootout gui/$UID "$PLIST" 2>/dev/null || true`,
    `    launchctl bootstrap gui/$UID "$PLIST" 2>/dev/null || true`,
    `    launchctl kickstart -k gui/$UID/com.agiterra.rove.daemon 2>/dev/null || true`,
    `    ;;`,
    `  reveal-logs)`,
    `    open -R "$HOME/.rove/daemon.log"`,
    `    ;;`,
    `  *)`,
    `    # Closed enum — silently ignore unknown actions.`,
    `    exit 0`,
    `    ;;`,
    `esac`,
    `HANDLER_EOF`,
    `chmod 700 "${S}URL_HANDLER"`,
    ``,
    `echo "URL handler written at ${S}URL_HANDLER"`,
    ``,
    `# ── step 14: generate AppleScript applet (paths substituted before compile) ─`,
    `# AppleScript compiled scripts cannot expand shell variables at runtime.
    # We substitute the absolute path NOW (heredoc with double-quoted opener)
    # so the compiled .scpt carries the literal path. (reviewer cheatsheet #15)`,
    `APPLET_DIR="${S}HOME/Applications"`,
    `APPLET_PATH="${S}APPLET_DIR/Rove Launcher.app"`,
    `APPLET_TMP="/tmp/rove-launcher.applescript"`,
    ``,
    `mkdir -p "${S}APPLET_DIR"`,
    ``,
    `# Double-quoted heredoc: $URL_HANDLER expands here in the shell, not inside
    # the compiled AppleScript. The result is a literal absolute path baked in.`,
    `cat > "${S}APPLET_TMP" <<OSA`,
    `on open location this_url`,
    `  do shell script "${S}URL_HANDLER " & quoted form of this_url`,
    `end open location`,
    `OSA`,
    ``,
    `osacompile -o "${S}APPLET_PATH" "${S}APPLET_TMP"`,
    `rm -f "${S}APPLET_TMP"`,
    ``,
    `echo "AppleScript applet compiled at ${S}APPLET_PATH"`,
    ``,
    `# ── step 15: patch Info.plist to declare rove:// URL scheme ─────────────`,
    `# PlistBuddy Add commands are not idempotent — delete first (ignore error),
    # then add the full chain cleanly.`,
    `INFO_PLIST="${S}APPLET_PATH/Contents/Info.plist"`,
    ``,
    `"${S}PLISTBUDDY" -c "Delete :CFBundleURLTypes" "${S}INFO_PLIST" 2>/dev/null || true`,
    `"${S}PLISTBUDDY" -c "Add :CFBundleURLTypes array" "${S}INFO_PLIST"`,
    `"${S}PLISTBUDDY" -c "Add :CFBundleURLTypes:0 dict" "${S}INFO_PLIST"`,
    `"${S}PLISTBUDDY" -c "Add :CFBundleURLTypes:0:CFBundleURLName string Rove Launcher" "${S}INFO_PLIST"`,
    `"${S}PLISTBUDDY" -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes array" "${S}INFO_PLIST"`,
    `"${S}PLISTBUDDY" -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes:0 string rove" "${S}INFO_PLIST"`,
    ``,
    `# Verify the plist is well-formed before we proceed.`,
    `if command -v plutil &>/dev/null; then`,
    `  plutil -lint "${S}INFO_PLIST" || {`,
    `    echo "error: Info.plist failed plutil lint after CFBundleURLTypes patch" >&2`,
    `    exit 1`,
    `  }`,
    `fi`,
    ``,
    `echo "Info.plist patched with CFBundleURLSchemes=rove"`,
    ``,
    `# ── step 16: ad-hoc codesign the applet ─────────────────────────────────`,
    `# Ad-hoc signing suppresses Gatekeeper warnings on this Mac.
    # Each user builds their own applet locally so ad-hoc is sufficient.`,
    `codesign -s - --force "${S}APPLET_PATH"`,
    ``,
    `echo "Applet signed (ad-hoc)."`,
    ``,
    `# ── step 17: register URL scheme with LaunchServices ─────────────────────`,
    `"${S}LSREGISTER" -R "${S}APPLET_PATH"`,
    ``,
    `echo "URL scheme rove:// registered with LaunchServices."`,
    `echo ""`,
    ``,
    `# ── success ───────────────────────────────────────────────────────────────`,
    `echo "=================================================================="`,
    `echo " Rove worker installed and running!"`,
    `echo "=================================================================="`,
    `echo ""`,
    `echo " Worker name : ${S}WORKER_NAME"`,
    `echo " Project     : ${S}PROJECT_ID"`,
    `echo " Token file  : ~/.rove/auth.token  (chmod 600)"`,
    `echo " Env file    : ~/.rove/env          (chmod 600)"`,
    `echo " Plist       : ~/Library/LaunchAgents/com.agiterra.rove.daemon.plist"`,
    `echo " Logs        : ~/.rove/daemon.log  /  ~/.rove/daemon.err"`,
    `echo " URL handler : ~/.rove/url-handler.sh  (chmod 700)"`,
    `echo " Applet      : ~/Applications/Rove Launcher.app"`,
    `echo ""`,
    `echo " Daemon installed and started. The dashboard at ${origin}/workers"`,
    `echo " should show your worker online within a few seconds."`,
    `echo ""`,
    `echo " The URL handler is installed. You can use the dashboard's"`,
    `echo " Resume / Pause / Restart / Show-logs actions without leaving the browser."`,
    `echo ""`,
    `echo " The daemon will restart automatically at login. If it ever stops,"`,
    `echo " use the dashboard controls to resume — no terminal trip needed."`,
    `echo "=================================================================="`,
  ];

  return lines.join("\n") + "\n";
}

export async function GET(request: Request) {
  const origin = getDashboardOrigin(request);
  const script = buildScript(origin);

  return new Response(script, {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-cache, must-revalidate",
    },
  });
}
