/**
 * Schemas for authoring artifacts (flows + personas) created via the
 * dashboard wizard or generated by the daemon. Shared between the
 * dashboard (validates form submission) and the daemon (validates the
 * Claude-generated JSON before writing it back to the job row).
 *
 * Keep this module dependency-free other than zod — it ships into both
 * a Next.js bundle and a Node CLI.
 */
import { z } from "zod";

export const FLOW_ID_PATTERN = /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*){1,3}$/;
export const PERSONA_ID_PATTERN = /^[a-z][a-z0-9_]*$/;

export const flowDraftSchema = z.object({
  flow_id: z
    .string()
    .min(3)
    .max(80)
    .regex(
      FLOW_ID_PATTERN,
      "flow_id must be lowercase dotted segments, e.g. scheduling.create_job.dispatcher",
    ),
  goal: z.string().min(10).max(500),
  entry_route: z.string().regex(/^\/[A-Za-z0-9/_\-:?=&.~%]*$/, "must start with '/'"),
  success_criteria: z.array(z.string().min(3).max(280)).min(1).max(8),
  template_id: z.string().min(1).max(64).optional(),
});
export type FlowDraft = z.infer<typeof flowDraftSchema>;

// ── Keyboard-navigation expectations (additive, 2026-05-14) ─────────────────
// Flow YAML may optionally declare expected Tab transitions so the
// accessibility + agent personas can assert focus order against intent
// rather than guess at it.
export const expectedKeyboardNavigationStepSchema = z.object({
  from_selector: z.string().min(1).max(240),
  to_selector: z.string().min(1).max(240),
  description: z.string().min(1).max(280).optional(),
});
export type ExpectedKeyboardNavigationStep = z.infer<
  typeof expectedKeyboardNavigationStepSchema
>;

export const expectedKeyboardNavigationSchema = z
  .array(expectedKeyboardNavigationStepSchema)
  .max(50);

export const flowDraftWithKeyboardNavSchema = flowDraftSchema.extend({
  expected_keyboard_navigation: expectedKeyboardNavigationSchema.optional(),
});
export type FlowDraftWithKeyboardNav = z.infer<typeof flowDraftWithKeyboardNavSchema>;

export const personaDraftSchema = z.object({
  persona_id: z
    .string()
    .min(3)
    .max(40)
    .regex(PERSONA_ID_PATTERN, "persona_id must be snake_case starting with a letter"),
  expertise: z.enum(["low", "medium", "high"]),
  shortcuts_allowed: z.boolean(),
  hovers_allowed: z.boolean(),
  retries_per_step: z.number().int().min(0).max(5),
  prompt_addendum: z.string().min(8).max(800),
});
export type PersonaDraft = z.infer<typeof personaDraftSchema>;

// ── Native-dialog expectations (additive, 2026-05-14) ───────────────────────
// Flow YAML may declare a dialog the persona expects to fire (or NOT to fire).
// The sink checks the dialog_payload on run_steps against this expectation
// and emits an `agent.expectation_match.confirm` style finding on a miss.
export const expectedNativeDialogSchema = z.object({
  type: z.enum(["alert", "confirm", "prompt", "beforeunload"]),
  text_matches: z.string().min(1).max(280).optional(),
  must_fire_before_step: z.string().min(1).max(120).optional(),
});
export type ExpectedNativeDialog = z.infer<typeof expectedNativeDialogSchema>;

export const flowExpectationsSchema = z.object({
  native_dialog: expectedNativeDialogSchema.optional(),
});
export type FlowExpectations = z.infer<typeof flowExpectationsSchema>;

export const flowDraftWithExpectationsSchema = flowDraftSchema.extend({
  expectations: flowExpectationsSchema.optional(),
});
export type FlowDraftWithExpectations = z.infer<typeof flowDraftWithExpectationsSchema>;

// ── Affordance exclusions (additive, 2026-05-14) ────────────────────────────
// Flow YAML may declare affordances that intentionally do NOT exist on a
// given URL pattern (e.g., "Delete is only on the list view, never on the
// detail view"). The walker still enumerates the page; the auto-finding
// emission consults this list and silences matching (URL, kind) pairs.
// Note in the run that the gap was silenced-by-flow so a future reviewer
// can re-evaluate.
//
// Per docs/proposals/affordance-gaps.md §5.
export const affordanceGapKindSchema = z.enum([
  "create",
  "read",
  "update",
  "delete",
  "undo",
  "recover",
  "navigate",
  "status",
  "confirm",
  "save_state",
  "empty",
  "error",
]);
export type AffordanceGapKind = z.infer<typeof affordanceGapKindSchema>;

export const affordanceExclusionSchema = z.object({
  url_pattern: z.string().min(1).max(240),
  do_not_expect: z.array(affordanceGapKindSchema).min(1).max(12),
  reason: z.string().min(3).max(280),
});
export type AffordanceExclusion = z.infer<typeof affordanceExclusionSchema>;

export const affordanceExclusionsSchema = z.array(affordanceExclusionSchema).max(50);

export const flowDraftWithAffordanceExclusionsSchema = flowDraftSchema.extend({
  affordance_exclusions: affordanceExclusionsSchema.optional(),
});
export type FlowDraftWithAffordanceExclusions = z.infer<
  typeof flowDraftWithAffordanceExclusionsSchema
>;
