import type { FindingsPayload } from "../types.js";

/**
 * A SinkAdapter routes parsed findings somewhere durable — a Markdown file,
 * GitHub Issues, Supabase, etc.
 *
 * Sinks may be composed. Each sink runs independently; one sink failing
 * does not block the others.
 */
export interface SinkAdapter {
  /** Stable identifier (e.g. "markdown", "github-issues", "supabase"). */
  readonly id: string;
  /** Human-readable label for log lines. */
  readonly label: string;
  /** Route the findings. Resolves with a per-sink result describing what was written. */
  route(input: SinkInput): Promise<SinkResult>;
}

export interface SinkInput {
  /** Validated findings payload (from `parseFindings`). */
  payload: FindingsPayload;
  /**
   * Stable run identifier (uuid v4). Generated by the CLI before dispatch so
   * the screenshots dir, the agent's references, and the row in the eval
   * store all share the same id.
   */
  runId: string;
  /** Dispatcher that produced these findings. */
  dispatcherId: string;
  /** Wall-clock when the walk started. */
  startedAt: Date;
  /** Wall-clock when the walk finished. */
  finishedAt: Date;
  /** Raw agent stdout — included for sinks that want to preserve the full transcript. */
  rawStdout: string;
  /**
   * Absolute path to the per-run screenshots directory the CLI created and
   * told the agent about. Sinks that upload screenshots resolve
   * `finding.screenshots[i].path` against this dir.
   */
  screenshotsDir: string;
  /**
   * Optional absolute path to the per-run MCP-proxy JSONL trajectory log.
   * When present, sinks that care (currently SupabaseSink) parse it to
   * populate run_steps + runs.metrics. Missing file → "no trajectory."
   */
  trajectoryLogPath?: string;
  /**
   * Git commit SHA at run time, if discoverable. Sinks that pin findings to
   * a code revision (Supabase) use this; sinks that don't (Markdown) ignore it.
   */
  commitSha?: string;
  /** Git branch at run time, if discoverable. */
  branch?: string;
}

export interface SinkResult {
  sinkId: string;
  /** Number of findings routed (after any per-sink filtering, e.g. severity threshold). */
  routedCount: number;
  /** Number of findings skipped (filter, dedup, etc.). */
  skippedCount: number;
  /** URLs / paths the sink produced (file paths, issue URLs, etc.). */
  artifacts: string[];
  /** True when the sink completed without error. */
  ok: boolean;
  /** Set when ok=false. */
  error?: string;
}
